name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.14
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:14-alpine3.14
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: log node version
        uses: docker://node:14-alpine3.14
        with:
          entrypoint: '/usr/local/bin/node'
          args: '-v'
      - uses: actions/checkout@v2
      - name: Show current directory content
        run: ls -la
      - name: log node version
        uses: docker://node:14-alpine3.14
        with:
          entrypoint: ./script.sh
          args: 'Some String'
  # node-docker:
  #   runs-on: ubuntu-latest
  #   # container:
  #   #   image: node:16-alpine3.14
  #   services:
  #     app:
  #       image: kgurley/node-api
  #       ports:
  #         - 3001:3000
  #     mongo:
  #       image: mongo
  #       ports:
  #         - '27017:27017'
  #   steps:
  #     - name: Log node version
  #       run: |
  #         node -v
  #         cat /etc/os-release
  #     - name: Post a user
  #       run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello", "address": "ddfd"}'''

  #     - name: Get Users
  #       run: curl http://localhost:3001/api/users
